### ISSUE TITLE
Tidak bisa membuat pilihan image di dropdown

### ISSUE THREAD

**Issue by arie1st** [plansys/plansys#5]
tidak bisa membuat pilihan dropdown sebagai image (ems bagian bor log)

**Comment by rizkyramadhan** [comment]
sudah bisa

**Comment by arie1st** [comment]
waktu image dipilih tidak muncul di filternya dan cuma muncul sourcenya aja


![filterimage](https://cloud.githubusercontent.com/assets/1841365/16260179/69563ffa-3890-11e6-9857-71a1adec857e.JPG)
